id: aws-cli
name: AWS Command Line Interface
version: 1.15.49
home: https://aws.amazon.com/cli/
installMethod: MSI
installers:
- location: https://s3.amazonaws.com/aws-cli/AWSCLI32.msi
- location: https://s3.amazonaws.com/aws-cli/AWSCLI64.msi
  architecture: x64
