id: mailspring
name: Mailspring
version: 1.2.1
home: https://getmailspring.com/
repo: https://github.com/Foundry376/Mailspring
installMethod: Squirrel
installers:
- location: https://updates.getmailspring.com/download?platform=win32
