id: brackets
name: Brackets
version: 1.13.17696
home: http://brackets.io/
repo: https://github.com/adobe/brackets/
license: MIT License
installMethod: MSI
installers:
- location: https://github.com/adobe/brackets/releases/download/release-1.13/Brackets.Release.1.13.msi
  sha256: a1020f55d4ec92c824ed6e5a3db941eaae6ffeb2334a77fa3465fe2736304a86
