id: plex-media-player
name: Plex Media Player
version: 1.12.1.4885
home: https://plex.tv
licence: GNU General Public License v2.0
installMethod: Wix
installers:
- location: https://downloads.plex.tv/plex-media-server/1.12.1.4885-1046ba85f/Plex-Media-Server-1.12.1.4885-1046ba85f.exe
  sha256: ea011d4799f11cf5e57c18bcac91d1588429f31271f50e3f6aa4164b5776acdc
