id: firefox
name: Mozilla Firefox
version: 61.0.1
home: https://www.mozilla.org/firefox/
installMethod: Custom
args:
  silent: -ms
installers:
- location: https://download.mozilla.org/?product=firefox-latest-ssl&os=win&lang=en-US
- location: https://download.mozilla.org/?product=firefox-latest-ssl&os=win64&lang=en-US
  architecture: x64
