id: firefox
name: Mozilla Firefox
version: 4.42
home: https://www.mozilla.org/firefox/
installMethod: NSIS
args:
  silent: -ms
installers:
- location: https://download.mozilla.org/?product=firefox-esr-latest&os=win&lang=en-US
- location: https://download.mozilla.org/?product=firefox-esr-latest&os=win64&lang=en-US
  architecture: x64
