id: google-chrome
name: Google-Chrome
installMethod: MSI
installers:
- location: https://dl.google.com/tag/s/dl/chrome/install/googlechromestandaloneenterprise.msi
- location: https://dl.google.com/tag/s/dl/chrome/install/googlechromestandaloneenterprise64.msi
  architecture: x64
