id: flash-player-ie
name: Flash Player Ie
version: 29.0.0.113
home: https://macromedia.com/
installMethod: MSI
installers:
- location: https://fpdownload.macromedia.com/get/flashplayer/pdc/29.0.0.113/install_flash_player_29_active_x.msi
  sha256: 9ba950605f78d03af24760eeacc546af88dc092c5ed229e3aac92901a3691278
