id: mp3tag
name: Mp3tag
version: 2.89.0
home: https://www.mp3tag.de/
installMethod: NSIS
installers:
- location: https://download.mp3tag.de/mp3tagv289setup.exe
  sha256: ef39c26d4ab1ae36a9ec17357cb1b9bedc9f20925088cb63c730c16c5d22babb
