id: qtox
name: qTox
version: 1.16.1
home: https://qtox.github.io/
repo: https://github.com/qTox/qTox/
license: GNU General Public License v3.0
installMethod: NSIS
installers:
- location: https://github.com/qTox/qTox/releases/download/v1.16.1/setup-qtox-i686-release.exe
  sha256: 86ca52f448b940c257023b014fed27df7d852407af7ed1a01831cc595501434c
- location: https://github.com/qTox/qTox/releases/download/v1.16.1/setup-qtox-x86_64-release.exe
  sha256: 2840d5f970ef52a218f7f07f3ecb780065abab0f6b044a18dc92b5848cc88404
  architecture: x64
