id: octave
name: GNU Octave
version: 4.2.2
home: https://gnu.org
installMethod: NSIS
installers:
- location: https://ftp.gnu.org/gnu/octave/windows/octave-4.2.2-w32-installer.exe
  sha256: 2d9d8de5ae399cb8649c16e12ff868b24d961dd644bcf86fe8604030dba0adad
- location: https://ftp.gnu.org/gnu/octave/windows/octave-4.2.2-w64-installer.exe
  sha256: 17879c35b83bf1682b2f468099a04b1c08a781af3f07773daa02d5cdc3a47e8d
  architecture: x64
