id: freefilesync
name: FreeFileSync
version: 10.2
home: https://freefilesync.org/
installMethod: Inno
installers:
- location: https://www.freefilesync.org/download/FreeFileSync_10.2_Windows_Setup.exe
  sha256: 1f083fc7f375ce325e281d7e689b6c694019da6d5b0c5d5e7cb547a5741ceea0
