id: smoke-test-manifest
name: Smoke Test App
version: 1.2.3
home: https://appget.net
installMethod: Custom
installers:
- location: https://appget.net/57db46fe-78b5-45be-9d99-fcdba094427b
isLatest: true
