id: malwarebytes
name: Malwarebytes
version: 3.4.5.2467
home: https://malwarebytes.com
installMethod: Inno
installers:
- location: https://downloads.malwarebytes.com/file/mbam_current/
  sha256: b443b573b8adeb55008e20a01221192bbc2faed15c2ec14aaf3c9c45b78247d9
