id: tableau-reader
name: Tableau Reader
version: 18.1.1421
home: https://www.tableau.com/products/reader
installMethod: Wix
installers:
- location: https://www.tableau.com/downloads/reader/pc64
  architecture: x64
