id: torguard
name: Torguard
home: https://torguard.biz/
installMethod: NSIS
installers:
- location: https://updates.torguard.biz/Software/Windows/torguard-setup-latest.exe
- location: https://updates.torguard.biz/Software/Windows/torguard-setup-latest.exe
  architecture: x64
