id: juju
name: Juju
version: 2.0.0
home: https://jaas.ai/
repo: https://github.com/juju/juju/
license: GNU Affero General Public License v3.0
installMethod: Inno
installers:
- location: https://launchpad.net/juju/2.6/2.6.9/+download/juju-setup-2.6.9-signed.exe
  sha256: 67ebfe518801fc9a36494bb2e687d4ec737cc724b89b6c1ea30f72afe53dfa10
