id: python3
name: Python3
version: 3.6.5
home: https://www.python.org/
installMethod: Wix
installers:
- location: https://www.python.org/ftp/python/3.6.5/python-3.6.5.exe
  sha256: caf33a6ade83cbae3314dea87595d29500ae2692cb656b587fba17009bedf3d8
- location: https://www.python.org/ftp/python/3.6.5/python-3.6.5-amd64.exe
  sha256: a518c95374bbdeec10a144a76a04b6e05ea3d8a0773aaf0581220abf7c9ad2c3
  architecture: x64
