id: brave
name: Brave
version: 0.23.31
home: https://brave.com/
repo: https://github.com/brave/browser-laptop/
installMethod: Squirrel
installers:
- location: https://laptop-updates.brave.com/latest/winia32
- location: https://laptop-updates.brave.com/latest/winx64
  architecture: x64
