id: brave
name: Brave
version: 0.23.19
home: https://brave.com/
installMethod: Squirrel
installers:
- location: https://laptop-updates.brave.com/latest/winia32
- location: https://laptop-updates.brave.com/latest/winx64
  architecture: x64
