id: steam
name: Steam
version: 2.10.91.91
home: https://store.steampowered.com/
installMethod: NSIS
installers:
- location: https://steamcdn-a.akamaihd.net/client/installer/SteamSetup.exe
  sha256: 029f918a29b2b311711788e8a477c8de529c11d7dba3caf99cbbde5a983efdad
