id: visual-studio-code
name: Visual Studio Code
version: 1.22.1
home: https://code.visualstudio.com/
installMethod: Inno
args:
  passive: /mergetasks=!runcode
  silent: /mergetasks=!runcode
installers:
- location: https://go.microsoft.com/fwlink/?LinkID=623230
  sha256: 0dd0e5e894adc73b1fbc730c8d67597ecb25c5e685e1a2c8d41e4b459b3842d9
- location: https://go.microsoft.com/fwlink/?Linkid=852157
  sha256: 2ea81dddde7e2da452bba97ae239a9579b261c189f57fac246f8c06c1fe641a5
  architecture: x64
