id: gog-galaxy
name: GOG Galaxy
version: 1.2.39.53
home: https://gog.com
installMethod: Inno
installers:
- location: https://content-system.gog.com/open_link/download?path=/open/galaxy/client/setup_galaxy_1.2.39.53.exe
  sha256: 8e39a1bde6891a3aeed09a2796c5134edbc85d280d4ee3249eddee66f824b9e5
