id: freecad
name: FreeCAD
version: 0.16.6706
home: https://www.freecadweb.org/
repo: https://github.com/FreeCAD/FreeCAD
installMethod: NSIS
installers:
- location: https://github.com/FreeCAD/FreeCAD/releases/download/0.16/FreeCAD.0.16.6706.f86a4e4-WIN-x86-installer.exe
  sha256: 15a84512855adb0ce86e78c5424a9cb589201369aa070acc7b9467621bc434ab
- location: https://github.com/FreeCAD/FreeCAD/releases/download/0.16/FreeCAD-0.16.6706.f86a4e4-WIN-x64_Installer-1.exe
  sha256: 25b5ddf0b7a40c401f260aeaf5cfbab992e243ae178b316cc82501fe706f3efb
  architecture: x64
