id: go
name: Go
version: 1.10.1
home: https://google.com
installMethod: MSI
installers:
- location: https://dl.google.com/go/go1.10.1.windows-386.msi
  sha256: 212e08ea4857e9fc308be2cb6cf3488ab26c83de36e46f4fefabf2296d8f9d48
- location: https://dl.google.com/go/go1.10.1.windows-amd64.msi
  sha256: b8cd4eb0c9ce2b7e50a2c69fb21bf8075b60fecc77c5caa1a60bdcb805f71803
  architecture: x64
