id: zettlr
name: Zettlr
version: 0.17.1
repo: https://github.com/Zettlr/Zettlr/
license: GNU General Public License v3.0
installMethod: NSIS
installers:
- location: https://github.com/Zettlr/Zettlr/releases/download/v0.17.1/Zettlr-win32-x64-0.17.1.exe
  sha256: 609f5b30337a991b371acd530b06de5072adcd15b32627cbb729c40002b34457
  architecture: x64
  minWindowsVersion: 6.1
