id: bunqdesktop
name: BunqDesktop
version: 0.8.11.723
home: https://bunqdesk.top/
repo: https://github.com/BunqCommunity/BunqDesktop/
license: MIT License
installMethod: NSIS
installers:
- location: https://github.com/BunqCommunity/bunqDesktop/releases/download/0.8.11/bunqDesktop.Setup.0.8.11.exe
  sha256: 1b3838dae9da144bb3709d083705310f98e9c468f46021daf918cd566b8afcff
  minWindowsVersion: 6.1
