id: git-lfs
name: Git LFS
version: 2.4
home: https://git-lfs.github.com/
repo: https://github.com/git-lfs/git-lfs
licence: MIT License
installMethod: Inno
installers:
- location: https://github.com/git-lfs/git-lfs/releases/download/v2.4.0/git-lfs-windows-2.4.0.exe
  sha256: 345034fc91459579370737201e991c7a2e8acabbb24d15577ecf588d071b1949
