id: gimp
name: GIMP
version: 2.10.4
home: https://www.gimp.org/
installMethod: Inno
installers:
- location: https://download.gimp.org/mirror/pub/gimp/v2.10/windows/gimp-2.10.4-setup-1.exe
  sha256: 608c12c66bccadbd46dd519b38337ebcda0cc6fc845bc3c8a943de43dccabfa9
